import Image from "next/image";

const About = () => {
    return <div className="grid grid-cols-1 lg:grid-cols-2">
        <p className="lg:col-span-2 text-primary text-center font-bold text-5xl mb-10">Acerca de nosotros</p>
        <p className="text-primary text-justify px-5 lg:pr-32 lg:px-16 font-bold text-lg">
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1

            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1
            TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 TEXTO1 </p>

        <div className="place-self-center relative lg:mr-16 w-10/12 aspect-square md:w-[600px]">
        <Image
            src="/ingenieroinstalapersiana.jpg"
            fill
            alt="Ingeniero instala persiana"
        />
        </div>
    </div>

}

export default About;